### ISSUE TITLE
Missed Navigation Safe Args for kotlin

### ISSUE THREAD

**Issue by rwqwr** [RedMadRobot/gradle-version-catalogs#2]
The [androidx](https://github.com/RedMadRobot/gradle-version-catalogs/blob/main/versions-androidx/libs.versions.toml) version catalog has `androidx.navigation.safeargs` but no `androidx.navigation.safeargs.kotlin`.
I think it would be useful to put them together.

**Comment by osipxd** [comment]
Thanks, I'll add it
